[package]
name = "workspaces"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1"
anyhow = "1.0"
base64 = "0.13"
chrono = "0.4.19"
dirs = "3.0.2"
hex = "0.4.2"
portpicker = "0.1.1"
rand = "0.8.4"
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-retry = "0.3"
url = { version = "2.2.2", features = ["serde"] }

near-crypto = "0.5"
near-primitives = "0.5"
near-jsonrpc-primitives = "0.5"
near-jsonrpc-client = { version = "0.1", features = ["sandbox"] }
near-sandbox-utils = { git = "https://github.com/near/sandbox" }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
borsh = "0.9"
