[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2018"

[dev-dependencies]
tokio = { version = "1.10.0", features = ["full"] }
runner = { version = "0.1.0", path = "../runner" }
serde_json = "1.0.64"


[[example]]
name = "nft"
path = "src/nft.rs"

[[example]]
name = "status_message"
path = "src/status_message.rs"
